properties([
    parameters([
	    choice(name: "TYPE", choices: ["nodejs-16", "nodejs-14", "nodejs-12"], description: "LANGUAGES"),
        choice(name: "SERVICE", choices: ["genric-frontend"], description: "services to be build"),
        choice(name: "PORT", choices: ["8081", "80", "8080", "8999"], description: "port to be used"),
    ])
])

env.MAINTAINER= "maintainer@geminisolutions.com"
env.BRANCH_CENTRALIZED_FILES="*/main"
env.SSH_LINK_CENTRALIZED_FILES="git@github.com:Gemini-Solutions/centralized-repo.git"

//Please specify the branch Name
if (params.SERVICE=="genric-frontend")
{
	env.BRANCH="*/dev"
	env.SSH_LINK='git@github.com:Gemini-Solutions/generic_workflow_frontend.git'
}

//To convert the service to lowercase as docker registry should be in lower case.
env.REGISTRY= params.SERVICE.toLowerCase()

//Docker and trivy builer Stage environment variable.
env.TRIVY_NODE = 'image_builder_trivy'
env.TRIVY_CONTAINER = 'docker-image-builder-trivy'

//Conditions based on languages
if (params.TYPE == "nodejs-16") 
{
    env.NODE_NAME = 'nodejs_runner_16' 
    env.CONTAINER_NAME = 'nodejs-16'
    env.STAGE_NAME = 'Nodejs_Build'
    env.CMD1= 'rm -rf package-lock.json'
    env.CMD2= 'npm cache clean --force'
    env.CMD3= 'npm install'
    env.CMD4= 'npm run build'
//     env.CMD5= 'export package=`cat angular.json | grep "outputPath" | awk -F"\"" '{print $2}'`'
    env.IMAGE=' nginx:1.17.1-alpine'
//     env.COPY_CMD= '.\\/build \\/usr\\/share\\/nginx\\/html' 
} 

else if (params.TYPE == "nodejs-14")
{
    env.NODE_NAME = 'nodejs_runner_14' 
    env.CONTAINER_NAME = 'nodejs-14'
    env.STAGE_NAME = 'Nodejs_Build'
    env.CMD1= 'rm -rf package-lock.json'
    env.CMD2= 'npm cache clean --force'
    env.CMD3= 'npm install'
    env.CMD4= 'npm run build'
//     env.CMD5= 'export package=`cat angular.json | grep "outputPath" | awk -F"\"" '{print $2}'`&& echo $package'
    env.IMAGE=' nginx:1.17.1-alpine'
//we need to add "\" before "/" to skip it, basically it will act as a de-limiter
// added:- one more back slash as, "\" it's a special character, which groovy doesn't support, so we need to skip it.
//     env.COPY_CMD= '.\\/build \\/usr\\/share\\/nginx\\/html' 
}
else
{
    env.NODE_NAME = 'nodejs_runner'
    env.CONTAINER_NAME = 'nodejs-12'
    env.STAGE_NAME = 'Nodejs_Build' 
    env.CMD1= 'rm -rf package-lock.json'
    env.CMD2= 'npm cache clean --force'
    env.CMD3= 'npm install'
    env.CMD4= 'npm run build'
//     env.CMD5= 'export package= `cat angular.json | grep "outputPath" | awk -f""" {print$2}`'
//     env.CMD5= 'export package=`cat angular.json | grep "outputPath" | awk -F"\"" '{print $2}'`&& echo $package'
    env.IMAGE=' nginx:1.17.1-alpine'
//     env.COPY_CMD= '.\\/build \\/usr\\/share\\/nginx\\/html'
}

node ("${env.NODE_NAME}") {
      stage('Repo_Checkout') {
             dir ("${env.SERVICE}") {
             checkout([$class: 'GitSCM', branches: [[name: "$BRANCH"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg:  [], \
    userRemoteConfigs: [[credentialsId: 'admingithub', url: "$SSH_LINK", poll: 'false']]])
             }
      }
	sh 'ls'
	stage("${env.STAGE_NAME}") {
	      container("${env.CONTAINER_NAME}") {
            dir ("${env.SERVICE}"){
		    if (env.NODE_NAME == 'nodejs_runner_16'  || env.NODE_NAME == 'nodejs_runner_14' || env.NODE_NAME == 'nodejs_runner')
			    {
			sh 'ls'
                  	sh 'env'
		  	        sh "${env.CMD1}"
			        sh "${env.CMD2}"
		  	        sh "${env.CMD3}"
			        sh "${env.CMD4}"
				sh "${env.CMD5}"
			    }
            }
           }
         }
       }


//Docker and Deployment Stage
node("${env.TRIVY_NODE}") {
       try {
        stage('Checkout_Centralized_Files') {
           dir ("${env.SERVICE}") {
               checkout([$class: 'GitSCM', 
               branches: [[name: "$BRANCH_CENTRALIZED_FILES"]], 
               doGenerateSubmoduleConfigurations: false, 
               extensions: [], 
               submoduleCfg:  [], 
               userRemoteConfigs: [[credentialsId: 'admingithub', 
               url: "$SSH_LINK_CENTRALIZED_FILES", 
               poll: 'false']]])
	       sh 'ls -la nodejs/'
// 	       sh 'cd Java'
	       sh 'pwd'
           }
       }
       stage('Build_image') {
                dir ("${env.SERVICE}") {
			container("${env.TRIVY_CONTAINER}") {
                  withCredentials([usernamePassword(credentialsId: 'docker_registry', passwordVariable: 'docker_pass', usernameVariable: 'docker_user')]) {
                //   sh 'echo TYPE is : $SERVICE'
		        //   sh 'sed -i -e "s/SERVICE/$SERVICE/g" DockerFile deployment-type.yaml' 
                  sh 'sed -i -e "s/PORT/$PORT/g" -e "s/REGISTRY/$REGISTRY/g" -e "s/COPY_CMD/$COPY_CMD/g" -e "s/IMAGE/$IMAGE/g" "s/package/$package/g" Typescript/DockerFile Typescript/Deployment-beta.yaml'
		          sh 'cat DockerFile'	  
                  sh 'docker image build -f Typescript/DockerFile --build-arg REGISTRY=$REGISTRY -t registry-np.geminisolutions.com/$REGISTRY:1.0-$BUILD_NUMBER -t registry-np.geminisolutions.com/$REGISTRY .'
                  sh 'trivy image -f json registry-np.geminisolutions.com/$REGISTRY:1.0-$BUILD_NUMBER > trivy-report.json' archiveArtifacts artifacts: 'trivy-report.json', onlyIfSuccessful: true
                  sh '''docker login -u $docker_user -p $docker_pass https://registry-np.geminisolutions.com'''
//                   sh 'docker push registry-np.geminisolutions.com/$REGISTRY:1.0-$BUILD_NUMBER'
//                   sh 'docker push registry-np.geminisolutions.com/$REGISTRY'
                  sh 'rm -rf build/'
               }
             }
          }
       }
       stage('Deployment_stage') {
               dir ("${env.SERVICE}") {
                   container("${env.TRIVY_CONTAINER}") {
                   kubeconfig(credentialsId: 'KubeConfigCred') {
//                    sh '/usr/local/bin/kubectl apply -f Typescript/Deployment-beta.yaml -n dev'
//                    sh '/usr/local/bin/kubectl rollout restart Deployment $REGISTRY -n dev'

                   }
                 }
               }
           }
    } finally {
         //sh 'echo current_image="registry-np.geminisolutions.com/helpdesk/server:1.0-$BUILD_NUMBER" > build.properties'
         //archiveArtifacts artifacts: 'build.properties', onlyIfSuccessful: true
         }
        }
