FROM openjdk:17-jdk-slim
MAINTAINER nikhil.sharma@geminisolutions.com
COPY target/timesheetsservice*.jar /home/
WORKDIR /home/
EXPOSE 8080
RUN mkdir -p /var/log/timesheet-svc
ENTRYPOINT ["java","-jar","timesheetsservice-0.0.2.jar"]
