apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokenmintingsvc
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tokenmintingsvc
  template:
    metadata:
      labels:
        app: tokenmintingsvc
    spec:
      containers:
        - image: registry-np.geminisolutions.com/tokenmintingsvc/tokenmintingsvc
          imagePullPolicy: Always
          name: tokenmintingsvc
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials-token-minting-svc
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials-token-minting-svc
                  key: password			  
      imagePullSecrets:
        - name: regcred
