apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec-backend
  namespace: dev
  labels:
    app: ec-backend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ec-backend
  template:
    metadata:
      labels:
        app: ec-backend
    spec:
      containers:
      - name: ec-backend
        image: registry-np.geminisolutions.com/ec_backend/ec_backend:latest
        ports:
        - name: ec-backend
          containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets: 
      - name: regcred
