node('image_builder_trivy') { 
   stage('amc_calculator_checkout') {
         dir ('amc_calculator') {
         checkout([$class: 'GitSCM', branches: [[name: '*/main']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg:  [], \
userRemoteConfigs: [[credentialsId: 'admingithub', url: 'git@github.com:Gemini-Solutions/AMC_Calculator.git']]])
         }
    }
  try {
    stage('Checkout_Centralized_Files') {
           dir ('amc_calculator/centralized') {
               checkout([$class: 'GitSCM', 
               branches: [[name: '*/main']], 
               doGenerateSubmoduleConfigurations: false, 
               extensions: [
	       	  [$class: 'PathRestriction', includedRegions: 'AMC_Calculator/**']
	       		], 
               submoduleCfg:  [], 
               userRemoteConfigs: [[credentialsId: 'admingithub', 
               url: 'git@github.com:Gemini-Solutions/centralized-repo.git', 
               poll: 'false']]])
	             sh 'ls -la'
           }
       }
   stage('Build_image') {
            dir ('amc_calculator') {
              container('docker-image-builder-trivy') {
                withCredentials([usernamePassword(credentialsId: 'docker_registry', passwordVariable: 'docker_pass', usernameVariable: 'docker_user')]) {
              sh 'docker image build -f centralized/AMC_Calculator/Dockerfile -t registry-np.geminisolutions.com/amc_calculator/amc_calculator_frontend/amc_calculator:1.0-$BUILD_NUMBER -t registry-np.geminisolutions.com/amc_calculator/amc_calculator_frontend/amc_calculator .'
              sh 'trivy image -f json --timeout 20m registry-np.geminisolutions.com/amc_calculator/amc_calculator_frontend/amc_calculator:1.0-$BUILD_NUMBER > trivy-report.json'
	      archiveArtifacts artifacts: 'trivy-report.json', onlyIfSuccessful: true
                   sh '''docker login -u $docker_user -p $docker_pass https://registry-np.geminisolutions.com'''
              sh 'docker push registry-np.geminisolutions.com/amc_calculator/amc_calculator_frontend/amc_calculator:1.0-$BUILD_NUMBER'
              sh 'docker push registry-np.geminisolutions.com/amc_calculator/amc_calculator_frontend/amc_calculator'
           }
         }
        }
        stage('Deployment_stage') {
               dir ('amc_calculator') {
                   container('docker-image-builder-trivy') {
                   kubeconfig(credentialsId: 'KubeConfigCred') {
                   sh '/usr/local/bin/kubectl apply -f centralized/AMC_Calculator/Deployment-beta.yaml -n dev'
                   sh '/usr/local/bin/kubectl rollout restart Deployment amc-calculator -n dev'

                   }
                   }
               }
           }
      }
  } finally {
     //sh 'echo current_image="registry-np.geminisolutions.com/resume_parser/resume_parser_backend/resume_parser:1.0-$BUILD_NUMBER" > build.properties'
     //archiveArtifacts artifacts: 'build.properties', onlyIfSuccessful: true
  }
    }
